apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: 674103662466.dkr.ecr.ap-south-1.amazonaws.com/test-cli:db8e3b10c1f0a7485c2f5876a66038af8f548e05
        name: test
        ports:
        - containerPort: 80
        resources: {}
